version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: my-pgadmin
    networks:
      - my_network
    ports:
      - "15432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - pgadmin_data:/pgadmin4

  postgres:
    image: postgres
    container_name: my-postgres
    networks:
      - my_network
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  configurator:
    image: alpine:latest
    container_name: configurator
    depends_on:
      - pgadmin
      - postgres
    networks:
      - my_network
    volumes:
      - pgadmin_data:/pgadmin4
    entrypoint: >
      /bin/sh -c "
      mkdir -p /pgadmin4 &&
      echo '{
        \"Servers\": {
          \"1\": {
            \"Name\": \"MyPostgres\",
            \"Group\": \"Servers\",
            \"Host\": \"my-postgres\",
            \"Port\": 5432,
            \"MaintenanceDB\": \"postgres\",
            \"Username\": \"postgres\",
            \"SSLMode\": \"prefer\"
          }
        }
      }' > /pgadmin4/servers.json"

networks:
  my_network:
    driver: bridge

volumes:
  pgadmin_data:
  postgres_data:
